### ISSUE TITLE
Background art pixelated in default Tile view

### ISSUE THREAD

**Issue by Enkak** [20GotoTen/es-theme-retrofix#1]
Hi and let me thank you first for this great theme. 

I use fanart backgrounds per game (1280 x 720 minimum) and noticed that in the games menu they look bad/pixelated since the code for size is small and inherited from grid thumbnails from what I understand looking at the code. Is there a way to make the game backgrounds look as good/clear as the ones in main/system menu?

Thank you in advance!

**Comment by 20GotoTen** [comment]
Hi Enkak, 

Unfortunately Retrofix hasn't been built to allow that at this time I'm afraid. Retrofix was created to pull in original game screenshots. I do like the idea though.

Maybe it could be a feature request for a later release? 

Thank you for your kind words and your feedback, it's really appreciated.

**Comment by Enkak** [comment]
Hi and many thanks for the reply. A feature request for a later release sounds good. :)

I understand that usually themes don't use much fanart backgrounds because it wasn't easily available in scrapers but lately that is changing and in my case I have already all the fanart for the games after months and months of searching and editing art. And a theme like Retrofix really shine when you use fanart backgrounds (similar to main menu) with the result looking very slick and modern.

If possible, I think it needs only a separate code for the area where the backgrounds/screenshots already appear to make it use `<size>1 1</size>` or near for them to look clear/crisp and not inherit the smaller size of thumbnails grid.

**Comment by 20GotoTen** [comment]
Added to investigate. Also, V2 has released, please let me know what you think!

**Comment by Enkak** [comment]
Hi! Thank you for the reply and let me know about V2 release. 

I noticed that the issue was gone at one point after updating the frontend/EmulationStation version. After updating the theme to V2 seems to be working good still and no pixelated background. Will do more testing.
