### ISSUE TITLE
Artwork too small with boxes view

### ISSUE THREAD

**Issue by JulianGomezN** [20GotoTen/es-theme-retrofix#12]
Artwork looks too small on the last update. I think it could be improved by making them bigger (Like in the first version), or placing them over the title and game info. Like this: 
![image](https://user-images.githubusercontent.com/124836834/228393117-7abc1908-312c-4eaa-9365-d735a1147d00.png)
Also, I wanted to say thanks for all the work you've put on the theme, the last update was such a big improvement and made it, at least for me, the best Batocera theme by far.

**Comment by 20GotoTen** [comment]
Hi, can you be a bit more specific? I've not changed any Artwork sizes. Thanks for the feedback!

**Comment by JulianGomezN** [comment]
This is the old one: 
![image](https://user-images.githubusercontent.com/124836834/228661538-fc472126-5684-4a48-a0cc-217011d90c5f.png)

This is the new one: 
![image](https://user-images.githubusercontent.com/124836834/228661617-066a3419-6e43-4977-bea0-de422ab9fe33.png)


Both have the same grid size, but for whatever reason now it's showing completely the artwork from the games at the sides.

**Comment by 20GotoTen** [comment]
Hmm, odd. Thanks for the screenshots, I'll take a look this weekend!
