### ISSUE TITLE
Gameboy

### ISSUE THREAD

**Issue by Refaze** [20GotoTen/es-theme-retrofix#16]
Using a Raspberry Pi 4 running Batocera V36.  I love this theme but when scrolling through Gameboy games its extremely leggy.  Not sure what's going on because other game folders work perfectly fine.  The Gameboy folder also ignores some theme settings such as turning video preview off. I did some digging and noticed the XML sheet is different then the other folders.

**Comment by 20GotoTen** [comment]
Hi, the gameboy XML is different as it uses a different video type to allow the recolouring of black and white videos to green. It might need to be removed for low power devices like the Pi so I'll look into that. The video playback settings I'll look into first as that should be a quick fix. Thanks for the feedback!

**Comment by 20GotoTen** [comment]
I've just checked the video delay function and it's working correctly. Have you updated recently? Retrofix has had some significant updates over the last few months.

**Comment by Refaze** [comment]
Updating fixed it thank ya!!  Thanks for letting me know about the Gameboy hopefully down the line it will run better on the PI.  Your theme is one of the best and thank you.
