### ISSUE TITLE
Offer a light theme and color options

### ISSUE THREAD

**Issue by Kekun** [20GotoTen/es-theme-retrofix#2]
Hi! I really like RetroFix, but it's a bit too gloomy for my liking, I'd love to see it have white background (maybe not `#ffffff` but something really close to it.

That would imply using black icons instead of white ones, I wonder if it can be done in a maintainable way… maybe by having a script automatically taking the white icon and replacing instances of `#ffffff` by `#000000` to generate the light theme variants, so only one set of icons have to be maintained?

Also, I'd love to be able to define an accent color, I know the Carbon theme allows to do that, it could be used as the marker when selecting a system or as the box selecting a game. I'd love to have options like pink or green, to match my cab's buttons. :)

**Comment by 20GotoTen** [comment]
Thanks for your feedback!

A light version and wider flexibility was in the original plan, but the consensus was a darker theme was easier on the eye. Here's a still from the early work, this will come in a later release.

![MD_Grid_View.png](https://user-images.githubusercontent.com/64983620/91769367-2afde600-ebd7-11ea-9b54-6df3dd70f4ef.png)

**Comment by Kekun** [comment]
It doesn't look bad at all. :) Glad to hear it will come! Again, accent colors would be a plus, but the light variant is more important.

**Comment by 20GotoTen** [comment]
A light option (or rather a separate theme) is planned. Also, V2 has released, let me k ow that you think! Thanks.
