### ISSUE TITLE
Add generic Batocera menu button icons

### ISSUE THREAD

**Issue by tomillr** [20GotoTen/es-theme-retrofix#8]
@20GotoTen Is your nice theme still under development? If so, I'd like to make a couple of suggestions on how to further improve the theme with some additional options:

The default Carbon theme uses "controller-agnostic" icons. Instead of labeling the buttons by letters, the icons use the cardinal directions (north/south/east/west) to indicate which button is assigned to a specific function:

![Bildschirmfoto 2022-03-07 um 13 05 00](https://user-images.githubusercontent.com/1507977/157031556-d430461c-1b72-43f2-911e-575603a1424d.png)

I find this method pretty handy, when switching between different controllers or when you hand the controller to someone who isn't aware that, for example, the displayed "A"-button prompt actually refers to the "B"-button on a connected Xbox controller.

Would it be possible, to add similar icons as a second batch of "generic" button icons in Retrofix?

**Comment by 20GotoTen** [comment]
Thank you for your feedback! I'll have a look at what could be done.

**Comment by 20GotoTen** [comment]
I've implemented a new system where you can choose in the theme settings what buttons you've set up (a,b,x,y) - try it out and let me know what you think!
